### ISSUE TITLE
[Tweets] Using Discord Embeds instead of the generated ones

### ISSUE THREAD

**Issue by Cabbidachi** [TrustyJAID/Trusty-cogs#100]
I know this is technically not an issue but it still bothers me. Is there someway to disable the generated embed and use the one that Discord generates instead? There are a lot of features missing in the embed that the cog itself generates and i kinda wonder if there is some way to just use the normal Discord Twitter embeds instead.

**Comment by TrustyJAID** [comment]
I didn't originally want to do this because I find discords embeds to have too much unnecessary information. I don't care about the number of likes and retweets a tweet has I just want the body of the tweet as best as I can and I've taken care to ensure everything I am capable of putting from a tweet is there (discord does not let bots embed videos, that's the only useful thing I could not add). Nevertheless this has been added as an option on a per channel basis for both commands and autotweet.

Edit: I also forgot to mention you will miss out on tweet replies by using discords embeds. My custom embeds will actually find the tweet a user is replying to alongside the reply tweet where discord only shows the reply tweet.

**Comment by Cabbidachi** [comment]
> Edit: I also forgot to mention you will miss out on tweet replies by using discords embeds. My custom embeds will actually find the tweet a user is replying to alongside the reply tweet where discord only shows the reply tweet.

Thats not a problem since i always disable them anyways. It's just that most of the tweets i get in my server include videos. So i just friendly wanted to ask if you could add the option to use discord embed instead and thanks for actually adding that ^w^.
