### ISSUE TITLE
[ExtendedModlog] Wrong info on certain modlogs

### ISSUE THREAD

**Issue by Fabian-Evolved** [TrustyJAID/Trusty-cogs#116]
I'll try to explain it the best i can.

Lets say someone types multiple messages, and i remove the latest message of that person. and then the person removes its own messages. in the modlog it shows that i removed all the messages. even though i didn't.

So basically i remove one first. and the modlog is correct on that one that i removed it. then the person themselfs remove the rest of the messages. however the modlog still shows my name on that i've removed said messages, even though i didn't.

This is a screenshot of what happened today: http://prntscr.com/ru8pb2
That user removed his own message, however because i removed a different message from another user a couple seconds before that. the bot named me as the person to remove the message. even though i didn't remove that message.

does any of this make sense? anyways does anyone have an idea on how i can fix that?

**Comment by TrustyJAID** [comment]
This is because it is impossible to accurately determine many of these events. ExtendedModLog does the best it can to try and provide information that may not be clearly visible but there's nothing in the API to link a mod deleting a message. What happens is the bot will see a message was deleted and then try checking the audit logs to see if that user recently had a message deleted by a mod and if they have it will suggest that the mod deleted it. This goes for more than just messages deleted as I said this is a "best guess" scenario for what happened to provide extra insight.
