### ISSUE TITLE
Rainbow.py

### ISSUE THREAD

**Issue by Note2Self** [TrustyJAID/Trusty-cogs#2]
Could you make rainbow role colour intervals fade into the next colour.

**Comment by TrustyJAID** [comment]
The best I could do is set it so that over a 2 minute interval it adjusts the colour to the next closest colour in a step. Because of the changing limits on using the API I don't feel comfortable making it change the colour every second or every second or even 10 seconds. So it won't look smooth at all but I can figure out how to make it do this regardless @Note2Self let me know. 😊

**Comment by TrustyJAID** [comment]
Rainbow roles is against the bot terms of service and considered spamming the API and will not be supported.
