### ISSUE TITLE
[ExtendedModLog] Add a setting to add onto cases with [p]reason

### ISSUE THREAD

**Issue by Jacob-1999** [TrustyJAID/Trusty-cogs#208]
**Is your feature request related to a problem? Please describe.**
Unless you consider limitation a problem, sure. Otherwise, no.

**Describe the solution you'd like**
A toggle-able setting to switch between changing the original reason of a case and adding onto a case, like additional notes. If someone has a long reason, it could make it easier instead of typing or copying the long reason, especially if you're on mobile and need to add additional details.

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
It'd be similar to Zeppelin's modlog embeds. It adds onto the case if someone was to do `[p]reason` instead of replacing the original reason.

**Comment by TrustyJAID** [comment]
the `[p]reason` command and that sort of functionality is part of Cores modlog. Extendedmodlog only extends cores basic modlog capabilities to track other options without relying too heavily on cores modlog. Bascially anything from extendedmodlog does not support adding reasons and the like and is only used for tracking purposes of things not for providing reasons for something happening since most of the things this tracks don't necessarily warrant a reason be added whereas kicks and bans do.
