### ISSUE TITLE
[starboard] Allow multiple starboards to use the same emoji

### ISSUE THREAD

**Issue by brandons209** [TrustyJAID/Trusty-cogs#226]
**Is your feature request related to a problem? Please describe.**
Starboards should be able to use the same emoji, for example I have two boards one SFW and one NSFW in my server. Both boards are whitelisted to different channels and post in different starboard channels. However, the way it is coded in `_update_stars` means that if two channels have the same emoji it could end prematurely before checking the other board.

**Describe the solution you'd like**
In `_update_star`, check every board that matches the emoji and call the same functions on it.

**Describe alternatives you've considered**
Using a different emoji for each board can work, but personally its a bit confusing to have to use different emojis for the same functionality, people don't like to read and having to use different emojis means people get confused and frustrated.

**Additional context**
If I wasn't so busy with college I would handle this right now, if this ends up hanging around I can maybe do a PR later in April.

**Comment by TrustyJAID** [comment]
I have no interest in this. The intent was to allow a server to have two different starboards/infinite pin-boards and that is tied to emojis. NSFW restrictions are in place for a reason; a message that is starred in a NSFW channel should not be re-posted in a non-NSFW channel. 

Allowing multiple starboards to utilize the same emoji complicates the logic flow. Which starboard should the emoji reaction *really* be using? The only information given in a reaction event is the message, emoji, and user. Only the emoji can be used to represent what starboard is used since each starboard has its own allowlist/blocklist that is setup after creation. There's no sane way to determine which starboard we should be using from the information provided on a reaction sent except the emoji being used. Furthermore we should attempt as much as possible to avoid duplicate posting. A starboard shouldn't have more than 1 event per-reaction, this means it shouldn't ever be posting in two separate channels at once.
