### ISSUE TITLE
[request] Change extendedmoglog edit message feature

### ISSUE THREAD

**Issue by Skyridr** [TrustyJAID/Trusty-cogs#28]
Awesome that an extended mod log system exists, thanks for that! However, is there a way you can change:

`Click to see new message`

To an actual message instead? Much more overview that way to see the edited messages that way rather than go to the edited message each time.

**Comment by TrustyJAID** [comment]
This behavior change has been asked for before. There is a limit to how much can fit inside embed fields and that's less than a potentially edited messages content. Fields can hold 1024 characters while the description field can hold 2048 characters. In an effort to provide *maximum* coverage for the changed message the jump link allows you to see what the new message is and the description field captures the whole original message before edits. You essentially see the final message anyways with the (edited) mark next to it. Otherwise you'll have people go and edit a message at 1500 characters and the important changes will be past the 1500 characters and no way to log that info alongside the original which was the intent of tracking edits.

**Comment by Skyridr** [comment]
Completely understandable!

Though, if there's a char limit in place. Wouldn't it be easier to set a character counter in to place? If < a certain char limit, post the entire edited message. If > the char limit, show "click to see new message". This way the feature would work both ways.

Though that would mean it has to count the characters per edited message.

**Comment by TrustyJAID** [comment]
Like I said, I don't like posting part of it since you can simply see the edited message in chat there's little reason to be looking through the logs except as a reference point so the most important thing to track is the original message before edits. The edited message is clearly visible as is in chat normally so people see that final message more often than not. If you have people going back and editing messages from a long time back then that's a different issue and still the jump links are better for that.
