### ISSUE TITLE
[reddit] always does not look like a valid subreddit.

### ISSUE THREAD

**Issue by jynxdarkspell** [TrustyJAID/Trusty-cogs#284]
No matter how I format the subreddit string so far, it always returns with 'whateverItype does not look like a valid subreddit."

To Reproduce
I've used:
([p] is substituted for prefix and whateveritype is substituted for the actual reddit name in these examples)
[p]redditset post whateveritype
[p]redditset post whateveritype channelname
[p]redditset post r/whateveritype
[p]redditset post r/whateveritype channelname
[p]redditset post /r/whateveritype
[p]redditset post /r/whateveritype channelname
[p]redditset post /r/whateveritype/
[p]redditset post /r/whateveritype/ channelname
[p]redditset post https://www/reddit.com/r/whateveritype
[p]redditset post https://www/reddit.com/r/whateveritype channelname
[p]redditset post https://www/reddit.com/r/whateveritype/
[p]redditset post https://www/reddit.com/r/whateveritype/ channelname

Expected behavior
What I expected to happen with one of these examples was to receive a message that the specified subreddit would now be posted in the channel the command was executed (it looks like I could execute the command and specify a discord channel, but it doesn't look like it's required)

Additional context
I did follow the installation instructions, installing reactivepy,and git+https://github.com/TrustyJAID/aPRAW@setup-fix with the latest version of the red discord bot in a python 3.9 virtualenv. I also followed the setup instructions, creating a new profile for the bot without 2FA, and setup my credentials as I was instructed. I've even restarted the bot afterwards. I've also re-verified that my credentials are correct and restarted my bot again. I am still getting the same error no matter how I attempt to add the subreddit to my channel.  Am I mistyping the post command?  If I am, an example of the post string would be most helpful (e.g. "[p]redditset post whatishouldtype"). If not mistyping the command, which one of the post command formats that I have used is supposed to be working, because none of my examples are?

**Comment by TrustyJAID** [comment]
Installing the cog through downloader should not require you to install reactivepy or aPRAW manually they should be installed automatically. All examples you provided are valid input for the subreddit. If you are providing a subreddit that is not publicly available you will see the error "`subreddit` does not look like a valid subreddit." If the subreddit is locked or otherwise unavailable you will see the error. You are providing an example of `whateveritype` which is not a valid subreddit anyways so of course it's not going to work. Please provide an *actual* subreddit you are having an issue with so I can diagnose it because if your reddit tokens are correctly entered then actual public subreddits do work.

**Comment by jynxdarkspell** [comment]
I appreciate your follow through!  I'm hosting redbot on a Linux machine, and have run across issues with other's cogs if I haven't manually installed the requirements, so that is why i did what i did.  The subreddit I am trying to use appears to be publicly available: r/wallstreetbets .  I've attempted all formats of the strings previously mentioned using wallstreetbets as well as trying WallStreetBets .

**Comment by TrustyJAID** [comment]
`[p]reddit new wallstreetbets` worked for me. Double check that you have correctly installed your API tokens and have not erroneously added spaces, or other characters when setting them via the `[p]set api` command. Sometimes people put `<>` around their tokens thinking it's required because of the example but that is meant to explain where you paste something that is required. Also ensure that you use exact naming the `[p]redditset creds` uses and ensure that your redirect uri is set correctly.

**Comment by jynxdarkspell** [comment]
I was fairly certain that the < > were unnecessary when inputting my credentials, and did not include those.  I am still getting the same error using [p]reddit new wallstreetbets, or any of the other reddit commands (hot random rising top). wallstreetbets does not look like a valid subreddit.

**Comment by jynxdarkspell** [comment]
the redirect url points to https://localhost , as well

**Comment by jynxdarkspell** [comment]
changing it to https://127.0.0.1 stll gives the same error, wallstreetbets does not look like a valid subreddit.

**Comment by TrustyJAID** [comment]
Is there anything in your console or logs that might explain what the actual issue is?

**Comment by jynxdarkspell** [comment]
Also, have re-input my credentials, verifying I am able to log into the bot account on reddit manually, so I know my password and username are correct.  As far as Red's console goes, I'm tailing the log, and I'm getting no errors in the console.  I haven't found a seperate log for the reddit cog, but am running updatedb at the moment to search for one again.

**Comment by jynxdarkspell** [comment]
As a side note, I created the api using the main account, and not the bot account...  Do you think that is the issue?

**Comment by TrustyJAID** [comment]
> As a side note, I created the api using the main account, and not the bot account... Do you think that is the issue?

Yes. The username and password you used must be tied to the same account as the api credentials you created.

**Comment by TrustyJAID** [comment]
As a side note from me, I prefer issues like this in my support channel on discord where more than just I will usually be able to respond and a lot more quickly. Server invite for the cog support server is here https://discord.gg/GET4DVk

**Comment by jynxdarkspell** [comment]
Lol~  Thank you so much Trusty!  Works a treat!
