### ISSUE TITLE
Twitter Cog throws 403 Error

### ISSUE THREAD

**Issue by davvok** [TrustyJAID/Trusty-cogs#301]
**Describe the bug**
When using the "autotweet" function i'm getting a [tweepy.asynchronous.streaming] Stream encountered HTTP Error: 403
in the console. I've only done a little research but apparently its releated to API v2 using different calls?

**To Reproduce**
1. Add the Tweets cog
2. Set up the cog
3. Set up the dev account
4. enter api keys
5. test with getuser (works fine)
6. set up autotweet
7. see the errors in the log

**Expected behavior**
Expected behaviour is for the autowteet function to display tweets

**Screenshots**
![image](https://user-images.githubusercontent.com/43211124/214591294-270d6e06-28e1-4a2e-8c9c-f48c5d864ccb.png)

**Additional context**

**Comment by TrustyJAID** [comment]
Twitter has shut down their v1.1 API in October so most of the cog on the master branch will not function at all. I do not plan to update the cog for twitters v2 API until Red 3.5.0 is released which is when I will merge my dpy-2.0 branch into master and the cog will update. I did this because none of the old autotweet system will work with twitters new v2 API system and Red 3.5.0 is introducing a lot of other breaking changes so it makes sense to break people at the same time with the new changes rather than try and get everything working for old tech.
