### ISSUE TITLE
Issues trying to get twitter cog to post tweets from user into channel

### ISSUE THREAD

**Issue by nmills3** [TrustyJAID/Trusty-cogs#312]
**Describe the bug**
I'm trying to get the tweets cog to post Tweets from MCMComicCon into a channel on my server and i'm just getting the following in the console and no tweets being sent to discord
![image](https://user-images.githubusercontent.com/26787639/236448340-0354ecff-73b5-4ad0-adfe-35adb14f6e62.png)
based on that error i'm assuming i've done something wrong but i have no idea what or how to fix it as the page linked to in the error message seems to describe how to set rules for tags and not users

**To Reproduce**
install twitter cog
add twitter api creds
run [p]twitter stream follow #⁠twitter MCMComicCon
check log

**Expected behavior**
The bot should post all tweets by MCMComicCon into the #twitter channel

**Screenshots**

**Additional context**

**Comment by nmills3** [comment]
Ok So adding the same user by doing
 \twitter stream addrule testRule from:MCMComicCon
and then
\twitter stream followrule #⁠twitter testRule
does work and sends the tweets to the server. it just seems to be adding the stream follow command that doesn't work

**Comment by nmills3** [comment]
after getting the cog working, i've managed to get one tweet from the account that was a retweet and then the next tweet they sent out resulted in an error and wasn't posted to discord. details in the attached log

[latest.log](https://github.com/TrustyJAID/Trusty-cogs/files/11407282/latest.log)

**Comment by nmills3** [comment]
forgot to mention i toggled like, retweet and reply buttons to OFF between the first working tweet and all the others that have not worked. i've now re-enabled the buttons to see if that fixes the issue

**Comment by nmills3** [comment]
so after turning on buttons, i managed to get the bot to post a reply they posted in response to someone. so maybe this is relayed to toggling off the buttons

**Comment by TrustyJAID** [comment]
You have already solved the original issue, twitters v2 streaming API requires you to define rules which are then sent to twitter so they can filter what tweets your application receives from the streaming endpoint. Your second issue, however, I don't believe is related to the buttons being added but rather an issue on twitters new v2 streaming API that I spent months trying to solve. The issue is that twitter internally disconnects your stream and the keepalive signal sent from the bot ends up registering as a brand new session. I believe the issue has gotten better over the last few months but I don't know for sure and it might be related to having more accounts followed that post more frequently. All this coupled with twitter now asking for a minimum $100/month for API read access has put this cog into a delicate situation.

**Comment by nmills3** [comment]
well so far i'm only following 1 user via the streaming bit. Also so far the only streaming disconnect i've had was at 16:06:48 (uk time) and i've not had any at the time of the other issues. I'll keep an eye on it for a day or 2 and update with how it goes

**Comment by CornFlakesPC** [comment]
Can someone help me out here? Maybe I'm blind or just simply stupid

I want to get tweets from one twitter account into one channel. Doenst matter if retweet, has a link in it or has media or not.

**Comment by TrustyJAID** [comment]
You have to define a rule first with `[p]twitter stream addrule` then you can follow that rule or the username you wanted in whatever discord channel. @botflakes

**Comment by nmills3** [comment]
can you clarify what twitter stream follow is meant to do? 
From the description in the help message, it sounds like it should basically do the same as adding a rule for just a single user and then following that rule. but that doesn't seem to be what that command does

**Comment by TrustyJAID** [comment]
`[p]twitter stream addrule` is required for twitter to filter your streams incoming tweets. The bot then needs to know who and where to send tweets to in discord. There's 2 ways of achieving this, `[p]twitter stream follow` allows you to designate a twitter username to be followed in a channel and is meant if you have a bunch of accounts added to one rule and want to split that stream into multiple discord channels, etc. `[p]twitter stream followrule` is more appropriate for most people running a private bot since they can utilize their 5 rules more effectively. Twitter was designed to be handled by public bots and private bots so for me having the option to designate a rule I can adjust for multiple people with a bunch of different accounts all being followed at once was important but for 99% of people running Red they can manage their rules more efficiently.

**Comment by nmills3** [comment]
ah ok that makes sense

**Comment by nmills3** [comment]
also as an update, i've been running the bot in buttons on mode for a day and so far there haven't been any more errors, i plan to leave it like this for one more day and then switch back to buttons off and see if that did cause my errors or if it was just coincidental that it started working when i toggled buttons back on

**Comment by TrustyJAID** [comment]
I am pretty sure it was coincidental. The Buttons not being on only affects the bot attempting to send tweets in discord and if it errored there it would raise an error you would see in your logs.

**Comment by nmills3** [comment]
well it attempting to send the tweet to discord was the issue. with the buttons on, it gets the tweets from twitter and posts them correctly, but with the buttons off, it would get the tweets but then in posting them to discord it was getting an error.

here's the error from the log file i uploaded yesterday
`[2023-05-05 15:00:25] [ERROR] red.trusty-cogs.Tweets: Could not post a tweet in <TextChannel id=977314257563701258 name='twitter' position=1 nsfw=False news=False category_id=977224593150468128> for account MCMComicCon
Traceback (most recent call last):
  File "/data/cogs/CogManager/cogs/tweets/tweets_api.py", line 595, in post_tweet_status
    await webhook.send(
  File "/data/venv/lib/python3.11/site-packages/discord/webhook/async_.py", line 1771, in send
    raise TypeError(f'expected view parameter to be of type View not {view.__class__.__name__}')
TypeError: expected view parameter to be of type View not NoneType`

**Comment by TrustyJAID** [comment]
That would be the error I am looking for to fix the issue.
