### ISSUE TITLE
Tweet Redirect URL for API

### ISSUE THREAD

**Issue by V1perN3st** [TrustyJAID/Trusty-cogs#324]
I am trying to setup Tweet on my bot, but to setup the API I need to have a redirect URL. I imagine the default using the loopback would be for if I was running the bot on the same computer. I am running Red on a remote Linux server that is headless. What would I use for the redirect, or how do I set that up when using a remote system?

**Comment by TrustyJAID** [comment]
So there's a couple things. Twitter requires payment in order to access the API now "basic" tier is $100/month and only allows accessing basic information about users, etc. in order to receive information about tweets it would cost $5000/month. The purpose of this cog was originally to post tweets directly in discord. I don't know if the send tweets functionality is restricted on the free tier or what features if any in the cog will still function on the free tier.

All that said, to utilize OAuth allowing you to log in you can set the redirect uri to `https://localhost/` the bot will accept the final URL, after authorizing, in DM's in order to save your credentials for access. This avoids the need to run the bot locally to go through the normal OAuth flow which you suggested. An alternative and more advanced method is to setup Dashboard using my PR version which adds generic OAuth support to dashboard for any cog to utilize. That's more advanced as it requires you to run Dashboard on the same server as the bot and install a custom version of both dashboard and the dashboard cog at the moment.

**Comment by V1perN3st** [comment]
To be honest, all I want it to do is post my tweets in my Discord Server. I don't plan on having it post from Discord to Twitter (or X if you want to call it that). I thought that had to be setup in order to read my Tweets and repost them in the Discord.

**Comment by TrustyJAID** [comment]
As far as I am aware in order for your tweets to appear in discord using this cog now it would cost you $5000/month. The OAuth setup just lets you send tweets from discord.
