### ISSUE TITLE
/hockey set defaultstate 

### ISSUE THREAD

**Issue by kjchrz03** [TrustyJAID/Trusty-cogs#329]
**Describe the bug**
When I am writing out /hockey set defaultstate periodrecap in my discord server, after I hit enter to post it, I get
"game updates set to Preview, Live, Goal, and Final"

**To Reproduce**
1./hockey set defaultstate
2. choose the channel
3. choose the state (periodrecap)
4. enter

**Expected behavior**
only to see the period recap for all teams

**Additional context**
it;s not just for period recaps; any option I choose isn't saved, all options end up engaged.

**Comment by TrustyJAID** [comment]
There's a couple things here. The "defaultstate" command is intended for newly created game day channels/threads. This will only start working when a new set of game day channels or threads are created the day after setting this command. There's an alternative command `[p]hockey set stateupdates` which requires you to specify a channel which you want to limit what game states are allowed in that channel. These are separate commands because one deals with recurring new channel/thread creation settings while the other handles modifying an existing channel with game updates.

With the addition of slash commands discord does not allow variadic input on arguments. It used to be that you could specify exactly what options you wanted but now the commands all function by adding or removing existing states to the current defaults. So if you just want period recap you need to remove everything except periodrecap from the settings.

**Comment by kjchrz03** [comment]
how do I remove the other states from the settings?
