### ISSUE TITLE
Destiny cog needs way to reauthenticate

### ISSUE THREAD

**Issue by Deanosim** [TrustyJAID/Trusty-cogs#76]
Bungie just had server problems and invalidated everyones logins, so now the Destiny cog doesn't work and I can't see any way to reauthenticate myself using the `[prefix] destiny user` I even tried updating the token for the cog with a new one, but that didn't help.

**Comment by Deanosim** [comment]
Managed to fix it, but that required unloading the cog, deleting the settings.json file and then restarting the entire bot. Not exactly an ideal solution.

**Comment by TrustyJAID** [comment]
The actual issue is that Bungie reset all user account refresh tokens due to an error in the API allowing people to access the incorrect accounts. I have not had time to look into fixing the cog since the change until now but the cog will now reset your auth tokens if this happens again and require you to re-auth automatically. Internally the cog will re-authenticate you automatically based on the refresh tokens but there was nothing it could do when refresh tokens expired.
